/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.pago;

import modelo.pago.Factura;
import modelo.reservacion.Reservacion;
import modelo.usuarios.Pasajero;
import modelo.viaje.Asiento;
import vistas.reservacion.JFListaReservacionPasajero;
import vistas.usuarios.JFPasajero;

/**
 *
 * @author Kevin
 */
public class JFFactura extends javax.swing.JFrame {
    Factura factura;
    JFListaReservacionPasajero lrp;
    Pasajero pasajero;
    
    /**
     * Creates new form JFFactura
     */
    public JFFactura(Reservacion reservacion, Pasajero pasajero){
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.pasajero = pasajero;
        this.lrp = new JFListaReservacionPasajero(pasajero);
        this.factura = new Factura(reservacion);
        this.factura.calcularTotal();    
        mostrarDatos(reservacion);
    }

    private void mostrarDatos(Reservacion reservacion){
        // EXTRAER LOS DATOS DEL USUARIO DE LA RESERVACIÓN-------------
        txtNombre.setText(reservacion.getCuenta().getUsuario().getNombre());
        txtApellido.setText(reservacion.getCuenta().getUsuario().getApellido());
        int numeroDeAsientos = 0;
        for (Asiento asiento : reservacion.getListaDeAsientos()){
            if (asiento!=null){
                numeroDeAsientos++;
            }
        }
        txtAsientos.setText(numeroDeAsientos+"");
        txtCodUnico.setText(reservacion.getCuenta().getUsuario().getCodUnico()+"");
        txtCorreo.setText(reservacion.getCuenta().getCorreo());
        txtValorIva.setText(factura.valorIva+"");
        txtValorServicio.setText(factura.valorServicio+"");
        txtValorTotal.setText(factura.valorTotal+"");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFactura = new javax.swing.JPanel();
        lblCorreo = new javax.swing.JLabel();
        txtValorIva = new javax.swing.JTextField();
        lblAsientos = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        lblValorServicio = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        lblValorIva = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        lblFactura = new javax.swing.JLabel();
        txtCodUnico = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtAsientos = new javax.swing.JTextField();
        lblCodUnico = new javax.swing.JLabel();
        txtValorServicio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFactura.setBorder(javax.swing.BorderFactory.createTitledBorder("Factura"));

        lblCorreo.setText("Correo");

        txtValorIva.setEditable(false);

        lblAsientos.setText("Asientos");

        txtValorTotal.setEditable(false);

        lblValorServicio.setText("Valor Servicio");

        btnContinuar.setText("Continuar");
        btnContinuar.setToolTipText("");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        lblValorIva.setText("IVA");

        lblValorTotal.setText("Total");

        txtNombre.setEditable(false);

        txtApellido.setEditable(false);

        lblFactura.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFactura.setText("Factura");

        txtCodUnico.setEditable(false);

        lblNombre.setText("Nombre");

        txtCorreo.setEditable(false);

        lblApellido.setText("Apellido");

        txtAsientos.setEditable(false);
        txtAsientos.setToolTipText("");

        lblCodUnico.setText("Código Unico");

        txtValorServicio.setEditable(false);

        javax.swing.GroupLayout pnlFacturaLayout = new javax.swing.GroupLayout(pnlFactura);
        pnlFactura.setLayout(pnlFacturaLayout);
        pnlFacturaLayout.setHorizontalGroup(
            pnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFacturaLayout.createSequentialGroup()
                .addGroup(pnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFacturaLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(pnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblApellido)
                                .addComponent(lblNombre))
                            .addComponent(lblCodUnico)
                            .addGroup(pnlFacturaLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(pnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValorServicio)
                                    .addComponent(lblAsientos)
                                    .addComponent(lblValorIva)
                                    .addComponent(lblValorTotal)
                                    .addComponent(lblCorreo))))
                        .addGap(173, 173, 173)
                        .addGroup(pnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(txtApellido)
                            .addComponent(txtCodUnico)
                            .addComponent(txtCorreo)
                            .addComponent(txtAsientos)
                            .addComponent(txtValorServicio)
                            .addComponent(txtValorIva)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                    .addGroup(pnlFacturaLayout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addGroup(pnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFactura))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        pnlFacturaLayout.setVerticalGroup(
            pnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFacturaLayout.createSequentialGroup()
                .addComponent(lblFactura)
                .addGap(40, 40, 40)
                .addGroup(pnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFacturaLayout.createSequentialGroup()
                        .addComponent(lblCodUnico)
                        .addGap(28, 28, 28)
                        .addGroup(pnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorreo)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(pnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAsientos)
                            .addComponent(txtAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(pnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorServicio)
                            .addComponent(txtValorServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(pnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorIva)
                            .addComponent(txtValorIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(pnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorTotal)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtCodUnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        this.setVisible(false);
        JFPasajero jFPasajero = new JFPasajero(pasajero);
        jFPasajero.setVisible(true);
    }//GEN-LAST:event_btnContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblAsientos;
    private javax.swing.JLabel lblCodUnico;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFactura;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblValorIva;
    private javax.swing.JLabel lblValorServicio;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JPanel pnlFactura;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtAsientos;
    private javax.swing.JTextField txtCodUnico;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtValorIva;
    private javax.swing.JTextField txtValorServicio;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
