/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.pago;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.pago.*;
import controladorBD.pago.SqlPago;
import controladorBD.reservacion.SqlReservacion;
import modelo.externo.Fecha;
import modelo.reservacion.Reservacion;
import modelo.usuarios.Conductor;
import modelo.usuarios.Pasajero;
import modelo.usuarios.Usuario;
import modelo.usuarios.Vehiculo;
import modelo.viaje.Viaje;
import vistas.reservacion.JFCrearReservación;
import vistas.reservacion.JFListaReservacionPasajero;

/**
 *
 * @author Kevin
 */
public class JFPago extends javax.swing.JFrame {
    PagoTransferencia pagoTransferencia;
    Reservacion reservacion;
    static Pasajero pasajero;
    Factura factura;
    SqlPago s = new SqlPago();
    /**
     * Creates new form JFPago
     */
    public JFPago(Reservacion reservacion) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.reservacion = reservacion;
        factura = new Factura(reservacion);
        this.pasajero = (Pasajero) reservacion.getCuenta();
        pagoTransferencia = new PagoTransferencia(factura, 20*60*1000);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPago = new javax.swing.JPanel();
        BtnPagoTransferencia = new javax.swing.JToggleButton();
        BtnPagoEfectivo = new javax.swing.JToggleButton();
        btnRegresar = new javax.swing.JButton();
        lblElegirPago = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPago.setBorder(javax.swing.BorderFactory.createTitledBorder("Método de Pago"));
        pnlPago.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlPago.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnPagoTransferencia.setText("Pago Transferencia");
        BtnPagoTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPagoTransferenciaActionPerformed(evt);
            }
        });
        pnlPago.add(BtnPagoTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 160, 30));

        BtnPagoEfectivo.setText("Pago Efectivo");
        BtnPagoEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPagoEfectivoActionPerformed(evt);
            }
        });
        pnlPago.add(BtnPagoEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 160, 30));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        pnlPago.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 403, 160, 30));

        lblElegirPago.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblElegirPago.setText("Elegir Método De Pago");
        pnlPago.add(lblElegirPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 265, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlPago, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlPago, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPagoTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPagoTransferenciaActionPerformed
        // TODO add your handling code here:
        
        // Una vez que se crea el pago;
        SqlReservacion sqlReservacion = new SqlReservacion();
        sqlReservacion.registrarReservacion(reservacion);
        
        JFListaReservacionPasajero jFListaReservacionPasajero = null;
        String tipoPago = "transferencia";
        System.out.println(tipoPago);
        try {
            s.insertarPago(factura, tipoPago);
            jFListaReservacionPasajero = new JFListaReservacionPasajero(pasajero);
        } catch (SQLException ex) {
            Logger.getLogger(JFPago.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        jFListaReservacionPasajero.setVisible(true);
        
    }//GEN-LAST:event_BtnPagoTransferenciaActionPerformed

    private void BtnPagoEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPagoEfectivoActionPerformed
        // TODO add your handling code here:
        
        SqlReservacion sqlReservacion = new SqlReservacion();
        sqlReservacion.registrarReservacion(reservacion);
        
        JOptionPane.showMessageDialog(rootPane,"Su pago será validado por el conductor","Pago Efectivo",1);
        String tipoPago = "efectivo";
        System.out.println(tipoPago);
        try {
            s.insertarPago(factura, tipoPago);
            this.setVisible(false);
            JFFactura jFactura = null;
            jFactura = new JFFactura(reservacion,pasajero);
            jFactura.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(JFPago.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnPagoEfectivoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); 
       
        JFCrearReservación jFCrearReservación = new JFCrearReservación(reservacion.getViaje(), pasajero);
        
        jFCrearReservación.setVisible(true); 
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /**
         * ******************Borrar*********************+
         */
        Usuario nuevoUsuario = new Usuario("Luis", "Narvaez", "0985381267", 201821107);
        Vehiculo vehiculo = new Vehiculo("PCM1478", "Kia rio", "negro", 2018, 5);
        Conductor cuentaConductor = null;
        if (vehiculo.validarAño()) {
            cuentaConductor = new Conductor("luis.narvaez@epn.edu.ec", "963mv",
                    nuevoUsuario, vehiculo);
        }
        Viaje nuevoViaje = new Viaje("Quito", "Santa Rosa",
                cuentaConductor.obtenerCantidadAsientos(), 0.625, cuentaConductor, new Fecha("2023-03-06 17:05:28"));
        cuentaConductor.crearViaje(nuevoViaje);

        Usuario nuevoUsuarioPasajero = new Usuario("O", "J", "0983973634", 202114325);
        Pasajero cuentaPasajero = new Pasajero("martha.ruiz@epn.edu.ec", "1234", nuevoUsuarioPasajero);

        Reservacion reservacion = new Reservacion(nuevoViaje, cuentaPasajero, 4);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new JFPago(reservacion,pasajero).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnPagoEfectivo;
    private javax.swing.JToggleButton BtnPagoTransferencia;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblElegirPago;
    private javax.swing.JPanel pnlPago;
    // End of variables declaration//GEN-END:variables
}
