/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.pago;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.pago.*;
import controladorBD.pago.SqlPago;
import controladorBD.reservacion.SqlReservacion;
import modelo.reservacion.Reservacion;
import modelo.usuarios.Pasajero;
import vistas.reservacion.JFCrearReservación;
import vistas.reservacion.JFListaReservacionPasajero;
import vistas.usuarios.JFPasajero;

/**
 *
 * @author Kevin
 */
public class JFPago extends javax.swing.JFrame {

    PagoTransferencia pagoTransferencia;
    Reservacion reservacion;
    static Pasajero pasajero;
    Factura factura;
    SqlPago sqlPago = new SqlPago();

    /**
     * Creates new form JFPago
     */
    public JFPago(Reservacion reservacion) {
        initComponents();
        this.setLocationRelativeTo(null);

        this.reservacion = reservacion;

        this.factura = new Factura(reservacion);
        this.pasajero = (Pasajero) reservacion.getCuenta();
        this.pagoTransferencia = new PagoTransferencia(factura, 20 * 60 * 1000, pasajero.getCreditos());
        this.factura.calcularTotal();

        txfValorTotal.setText(factura.valorTotal + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPago = new javax.swing.JPanel();
        BtnPagoTransferencia = new javax.swing.JToggleButton();
        BtnPagoEfectivo = new javax.swing.JToggleButton();
        btnRegresar = new javax.swing.JButton();
        lblElegirPago = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        txfValorTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPago.setBorder(javax.swing.BorderFactory.createTitledBorder("Método de Pago"));
        pnlPago.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlPago.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnPagoTransferencia.setText("Pago Transferencia");
        BtnPagoTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPagoTransferenciaActionPerformed(evt);
            }
        });
        pnlPago.add(BtnPagoTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 160, 30));

        BtnPagoEfectivo.setText("Pago Efectivo");
        BtnPagoEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPagoEfectivoActionPerformed(evt);
            }
        });
        pnlPago.add(BtnPagoEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 160, 30));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        pnlPago.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 160, 30));

        lblElegirPago.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblElegirPago.setText("Elegir Método De Pago");
        pnlPago.add(lblElegirPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 265, 50));

        lblValorTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblValorTotal.setText("Valor total");
        pnlPago.add(lblValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        txfValorTotal.setEditable(false);
        txfValorTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlPago.add(txfValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlPago, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlPago, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPagoTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPagoTransferenciaActionPerformed
        SqlReservacion sqlReservacion = new SqlReservacion();
        sqlReservacion.registrarReservacion(reservacion);

        pasajero.crearReservacion(reservacion);

        String tipoPago = "transferencia";
        System.out.println(tipoPago);
        try {
            sqlPago.registrarFactura(factura);
            sqlPago.insertarPago(factura, tipoPago);
        } catch (SQLException ex) {
            Logger.getLogger(JFPago.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        JFPasajero jFPasajero = new JFPasajero(pasajero);
        jFPasajero.setVisible(true);
    }//GEN-LAST:event_BtnPagoTransferenciaActionPerformed

    private void BtnPagoEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPagoEfectivoActionPerformed
        SqlReservacion sqlReservacion = new SqlReservacion();
        sqlReservacion.registrarReservacion(reservacion);

        JOptionPane.showMessageDialog(rootPane, "Su pago será validado por el conductor", "Pago Efectivo", 1);

        String tipoPago = "efectivo";
        System.out.println(tipoPago);
        try {
            sqlPago.registrarFactura(factura);
            sqlPago.insertarPago(factura, tipoPago);
            this.setVisible(false);
            JFFactura jFactura = new JFFactura(reservacion, pasajero);
            jFactura.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(JFPago.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnPagoEfectivoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        JFCrearReservación jFCrearReservación = new JFCrearReservación(reservacion.getViaje(), pasajero);
        jFCrearReservación.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnPagoEfectivo;
    private javax.swing.JToggleButton BtnPagoTransferencia;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblElegirPago;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JPanel pnlPago;
    private javax.swing.JTextField txfValorTotal;
    // End of variables declaration//GEN-END:variables
}
