/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.pago;

import controladorBD.pago.SqlPago;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.externo.Fecha;
import modelo.pago.Factura;
import modelo.pago.PagoEfectivo;
import modelo.reservacion.Reservacion;
import modelo.usuarios.Conductor;
import modelo.usuarios.Pasajero;
import modelo.usuarios.Usuario;
import modelo.usuarios.Vehiculo;
import modelo.viaje.Viaje;

/**
 *
 * @author Kevin
 */
public class JFPagoEfectivo extends javax.swing.JFrame {
    PagoEfectivo pagoEfectivo;
    Factura factura;
    JFPago jPago;
    static Pasajero pasajero;
    SqlPago s = new SqlPago();

    public JFPagoEfectivo(Reservacion reservacion, Pasajero pasajero){
        initComponents();
        this.setLocationRelativeTo(null);
        factura = new Factura(reservacion);
        pagoEfectivo = new PagoEfectivo(factura);
        jPago = new JFPago(reservacion, pasajero);
        this.pasajero = pasajero;
        factura.calcularTotal();
        txtMontoaCancelar.setText(factura.valorTotal+"");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPagoEfectivo = new javax.swing.JPanel();
        lblPagoEfectivo = new javax.swing.JLabel();
        lblMontoACancelar = new javax.swing.JLabel();
        txtMontoaCancelar = new javax.swing.JTextField();
        btnPagoRealizado = new javax.swing.JButton();
        btnRegresarPE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPagoEfectivo.setBorder(javax.swing.BorderFactory.createTitledBorder("Pago Efectivo"));

        lblPagoEfectivo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPagoEfectivo.setText("Pago Efectivo");

        lblMontoACancelar.setText("Monto a Cancelar");

        btnPagoRealizado.setText("Pago Realizado");
        btnPagoRealizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoRealizadoActionPerformed(evt);
            }
        });

        btnRegresarPE.setText("Regresar");
        btnRegresarPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPagoEfectivoLayout = new javax.swing.GroupLayout(pnlPagoEfectivo);
        pnlPagoEfectivo.setLayout(pnlPagoEfectivoLayout);
        pnlPagoEfectivoLayout.setHorizontalGroup(
            pnlPagoEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagoEfectivoLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(pnlPagoEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPagoEfectivoLayout.createSequentialGroup()
                        .addGroup(pnlPagoEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPagoEfectivoLayout.createSequentialGroup()
                                .addComponent(btnPagoRealizado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(btnRegresarPE, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPagoEfectivoLayout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(lblPagoEfectivo)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlPagoEfectivoLayout.createSequentialGroup()
                        .addComponent(lblMontoACancelar)
                        .addGap(140, 140, 140)
                        .addComponent(txtMontoaCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addGap(192, 192, 192))))
        );
        pnlPagoEfectivoLayout.setVerticalGroup(
            pnlPagoEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagoEfectivoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblPagoEfectivo)
                .addGap(104, 104, 104)
                .addGroup(pnlPagoEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMontoaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMontoACancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addGroup(pnlPagoEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagoRealizado, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresarPE, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPagoEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPagoEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagoRealizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoRealizadoActionPerformed
        try {
            s.registrarFactura(factura);
            JOptionPane.showMessageDialog(rootPane, "Pago Confirmado","Pago Efectivo",1);
            // MOSTRAR LISTA DE VIAJES
        this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(JFPagoEfectivo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPagoRealizadoActionPerformed

    private void btnRegresarPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPEActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        // MOSTRAR LISTA DE VIAJES
    }//GEN-LAST:event_btnRegresarPEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPagoEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPagoEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPagoEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPagoEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /**
         * ******************Borrar*********************+
         */
        Usuario nuevoUsuario = new Usuario("Luis", "Narvaez", "0985381267", 201821107);
        Vehiculo vehiculo = new Vehiculo("PCM1478", "Kia rio", "negro", 2018, 5);
        Conductor cuentaConductor = null;
        if (vehiculo.validarAño()) {
            cuentaConductor = new Conductor("luis.narvaez@epn.edu.ec", "963mv",
                    nuevoUsuario, vehiculo);
        }
        Viaje nuevoViaje = new Viaje("Quito", "Santa Rosa",
                cuentaConductor.obtenerCantidadAsientos(), 0.625, cuentaConductor, new Fecha("2023-03-06 17:05:28"));
        cuentaConductor.crearViaje(nuevoViaje);

        Usuario nuevoUsuarioPasajero = new Usuario("O", "J", "0983973634", 202114325);
        Pasajero cuentaPasajero = new Pasajero("martha.ruiz@epn.edu.ec", "1234", nuevoUsuarioPasajero);

        Reservacion reservacion = new Reservacion(nuevoViaje, cuentaPasajero, 4);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFPagoEfectivo(reservacion, pasajero).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagoRealizado;
    private javax.swing.JButton btnRegresarPE;
    private javax.swing.JLabel lblMontoACancelar;
    private javax.swing.JLabel lblPagoEfectivo;
    private javax.swing.JPanel pnlPagoEfectivo;
    private javax.swing.JTextField txtMontoaCancelar;
    // End of variables declaration//GEN-END:variables
}
