
package vistas.ranking;

import javax.swing.Timer;
import controladorBD.ranking.SqlCalificacion;
import controladorBD.ranking.SqlComentario;
import modelo.ranking.Calificacion;
import modelo.ranking.CalificacionConductor;
import modelo.ranking.CalificacionExperiencia;
import modelo.ranking.CalificacionVehiculo;


public class JFrameCalificacion extends javax.swing.JFrame {

    /**
     * Creates new form vistaCalificacion
     */
    private Calificacion calificacion;
    
    public JFrameCalificacion(Calificacion calificacion) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.calificacion = calificacion;
        
        this.PanelCalificacionVehiculo.setVisible(false);
        this.PanelCalificacionExperiencia.setVisible(false);
        this.PanelAgradecimiento.setVisible(false);  
    }
    
    //borrar
    public JFrameCalificacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCalificacionConductor = new javax.swing.JPanel();
        jLabelCalificacionConductor = new javax.swing.JLabel();
        jComboBoxCalificacionConductor = new javax.swing.JComboBox<>();
        jButtonCalificacionConductor = new javax.swing.JButton();
        PanelCalificacionVehiculo = new javax.swing.JPanel();
        jLabelCalificacionVehiculo = new javax.swing.JLabel();
        jComboBoxCalificacionVehiculo = new javax.swing.JComboBox<>();
        jButtonCalificacionVehiculo = new javax.swing.JButton();
        PanelCalificacionExperiencia = new javax.swing.JPanel();
        jComboBoxCalificacionExperiencia = new javax.swing.JComboBox<>();
        jLabelCalificacionExperiencia = new javax.swing.JLabel();
        jButtonCalificacionExperiencia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCalificacionExperiencia = new javax.swing.JTextArea();
        PanelAgradecimiento = new javax.swing.JPanel();
        jLabelAgradecimiento = new javax.swing.JLabel();
        jLabelAgradecimiento1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        PanelCalificacionConductor.setBackground(new java.awt.Color(255, 255, 255));
        PanelCalificacionConductor.setForeground(new java.awt.Color(255, 255, 255));

        jLabelCalificacionConductor.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelCalificacionConductor.setForeground(new java.awt.Color(43, 63, 94));
        jLabelCalificacionConductor.setText("<html> <style> p {text-align: center;} </style><p>¿Qué tal te pareció el<br/>conductor?</p></html> ");

        jComboBoxCalificacionConductor.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxCalificacionConductor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBoxCalificacionConductor.setForeground(new java.awt.Color(43, 63, 94));
        jComboBoxCalificacionConductor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 estrella", "2 estrellas", "3 estrellas", "4 estrellas", "5 estrellas" }));
        jComboBoxCalificacionConductor.setBorder(null);

        jButtonCalificacionConductor.setBackground(new java.awt.Color(255, 51, 102));
        jButtonCalificacionConductor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonCalificacionConductor.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalificacionConductor.setText("Siguiente");
        jButtonCalificacionConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalificacionConductorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCalificacionConductorLayout = new javax.swing.GroupLayout(PanelCalificacionConductor);
        PanelCalificacionConductor.setLayout(PanelCalificacionConductorLayout);
        PanelCalificacionConductorLayout.setHorizontalGroup(
            PanelCalificacionConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCalificacionConductorLayout.createSequentialGroup()
                .addGroup(PanelCalificacionConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCalificacionConductorLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabelCalificacionConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCalificacionConductorLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jComboBoxCalificacionConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCalificacionConductorLayout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jButtonCalificacionConductor)))
                .addGap(250, 250, 250))
        );
        PanelCalificacionConductorLayout.setVerticalGroup(
            PanelCalificacionConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCalificacionConductorLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabelCalificacionConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jComboBoxCalificacionConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jButtonCalificacionConductor)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        PanelCalificacionVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        PanelCalificacionVehiculo.setForeground(new java.awt.Color(255, 255, 255));

        jLabelCalificacionVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelCalificacionVehiculo.setForeground(new java.awt.Color(43, 63, 94));
        jLabelCalificacionVehiculo.setText("<html> <style> p {text-align: center;} </style><p>¿Qué tal te pareció el<br/>estado del vehículo?</p></html> ");

        jComboBoxCalificacionVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxCalificacionVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBoxCalificacionVehiculo.setForeground(new java.awt.Color(43, 63, 94));
        jComboBoxCalificacionVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 estrella", "2 estrellas", "3 estrellas", "4 estrellas", "5 estrellas" }));
        jComboBoxCalificacionVehiculo.setBorder(null);

        jButtonCalificacionVehiculo.setBackground(new java.awt.Color(255, 51, 102));
        jButtonCalificacionVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonCalificacionVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalificacionVehiculo.setText("Siguiente");
        jButtonCalificacionVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalificacionVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCalificacionVehiculoLayout = new javax.swing.GroupLayout(PanelCalificacionVehiculo);
        PanelCalificacionVehiculo.setLayout(PanelCalificacionVehiculoLayout);
        PanelCalificacionVehiculoLayout.setHorizontalGroup(
            PanelCalificacionVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCalificacionVehiculoLayout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addGroup(PanelCalificacionVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCalificacionVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelCalificacionVehiculoLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jComboBoxCalificacionVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCalificacionVehiculoLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jButtonCalificacionVehiculo)))
                .addGap(211, 211, 211))
        );
        PanelCalificacionVehiculoLayout.setVerticalGroup(
            PanelCalificacionVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCalificacionVehiculoLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabelCalificacionVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jComboBoxCalificacionVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jButtonCalificacionVehiculo)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        PanelCalificacionExperiencia.setBackground(new java.awt.Color(255, 255, 255));
        PanelCalificacionExperiencia.setForeground(new java.awt.Color(255, 255, 255));

        jComboBoxCalificacionExperiencia.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxCalificacionExperiencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBoxCalificacionExperiencia.setForeground(new java.awt.Color(43, 63, 94));
        jComboBoxCalificacionExperiencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 estrella", "2 estrellas", "3 estrellas", "4 estrellas", "5 estrellas" }));
        jComboBoxCalificacionExperiencia.setBorder(null);

        jLabelCalificacionExperiencia.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelCalificacionExperiencia.setForeground(new java.awt.Color(43, 63, 94));
        jLabelCalificacionExperiencia.setText("<html> <style> p {text-align: center;} </style><p>¿Qué tal te pareció la<br/>experiencia?</p></html> ");

        jButtonCalificacionExperiencia.setBackground(new java.awt.Color(255, 51, 102));
        jButtonCalificacionExperiencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonCalificacionExperiencia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalificacionExperiencia.setText("Siguiente");
        jButtonCalificacionExperiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalificacionExperienciaActionPerformed(evt);
            }
        });

        jTextAreaCalificacionExperiencia.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaCalificacionExperiencia.setColumns(20);
        jTextAreaCalificacionExperiencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaCalificacionExperiencia.setForeground(new java.awt.Color(43, 63, 94));
        jTextAreaCalificacionExperiencia.setLineWrap(true);
        jTextAreaCalificacionExperiencia.setRows(5);
        jTextAreaCalificacionExperiencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese sus comentarios!", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(43, 63, 94))); // NOI18N
        jScrollPane1.setViewportView(jTextAreaCalificacionExperiencia);

        javax.swing.GroupLayout PanelCalificacionExperienciaLayout = new javax.swing.GroupLayout(PanelCalificacionExperiencia);
        PanelCalificacionExperiencia.setLayout(PanelCalificacionExperienciaLayout);
        PanelCalificacionExperienciaLayout.setHorizontalGroup(
            PanelCalificacionExperienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCalificacionExperienciaLayout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addGroup(PanelCalificacionExperienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCalificacionExperienciaLayout.createSequentialGroup()
                        .addComponent(jButtonCalificacionExperiencia)
                        .addGap(336, 336, 336))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCalificacionExperienciaLayout.createSequentialGroup()
                        .addComponent(jComboBoxCalificacionExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCalificacionExperienciaLayout.createSequentialGroup()
                        .addGroup(PanelCalificacionExperienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCalificacionExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(224, 224, 224))))
        );
        PanelCalificacionExperienciaLayout.setVerticalGroup(
            PanelCalificacionExperienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCalificacionExperienciaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabelCalificacionExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jComboBoxCalificacionExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButtonCalificacionExperiencia)
                .addGap(85, 85, 85))
        );

        PanelAgradecimiento.setBackground(new java.awt.Color(255, 255, 255));
        PanelAgradecimiento.setForeground(new java.awt.Color(255, 255, 255));

        jLabelAgradecimiento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelAgradecimiento.setForeground(new java.awt.Color(43, 63, 94));
        jLabelAgradecimiento.setText("<html> <style> p {text-align: center;} </style><p>Sus comentarios nos ayudan para mejorar nuestro servicio. </p></html> ");

        jLabelAgradecimiento1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelAgradecimiento1.setForeground(new java.awt.Color(43, 63, 94));
        jLabelAgradecimiento1.setText("<html> <style> p {text-align: center;} </style><p>¡Gracias por evaluarnos!</p></html> ");

        javax.swing.GroupLayout PanelAgradecimientoLayout = new javax.swing.GroupLayout(PanelAgradecimiento);
        PanelAgradecimiento.setLayout(PanelAgradecimientoLayout);
        PanelAgradecimientoLayout.setHorizontalGroup(
            PanelAgradecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgradecimientoLayout.createSequentialGroup()
                .addGroup(PanelAgradecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAgradecimientoLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabelAgradecimiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAgradecimientoLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabelAgradecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        PanelAgradecimientoLayout.setVerticalGroup(
            PanelAgradecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgradecimientoLayout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(jLabelAgradecimiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabelAgradecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCalificacionConductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelCalificacionVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelCalificacionExperiencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelAgradecimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCalificacionConductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelCalificacionVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelCalificacionExperiencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelAgradecimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalificacionConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalificacionConductorActionPerformed
        this.PanelCalificacionConductor.setVisible(false);
        this.PanelCalificacionVehiculo.setVisible(true);
        CalificacionConductor cC = new CalificacionConductor((this.calificacion.getViaje()));
        cC.ingresar(jComboBoxCalificacionConductor.getSelectedIndex()+1);
        SqlCalificacion sqlCalificacion = new SqlCalificacion(cC);
        sqlCalificacion.ingresarCalificacion(0);
        
    }//GEN-LAST:event_jButtonCalificacionConductorActionPerformed

    private void jButtonCalificacionVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalificacionVehiculoActionPerformed
        this.PanelCalificacionVehiculo.setVisible(false);
        this.PanelCalificacionExperiencia.setVisible(true);
        CalificacionVehiculo ch = new CalificacionVehiculo(this.calificacion.getViaje());
        ch.ingresar(jComboBoxCalificacionVehiculo.getSelectedIndex()+1);
        SqlCalificacion sqlCalificacion = new SqlCalificacion(ch);
        sqlCalificacion.ingresarCalificacion(1);
    }//GEN-LAST:event_jButtonCalificacionVehiculoActionPerformed

    private void jButtonCalificacionExperienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalificacionExperienciaActionPerformed
        this.PanelCalificacionExperiencia.setVisible(false);
        this.PanelAgradecimiento.setVisible(true);

        CalificacionExperiencia cE = new CalificacionExperiencia(this.calificacion.getViaje());
        cE.ingresar(jComboBoxCalificacionExperiencia.getSelectedIndex()+1);
        cE.agregarComentario(jTextAreaCalificacionExperiencia.getText());
        SqlCalificacion sqlCalificacion = new SqlCalificacion(cE);
        sqlCalificacion.ingresarCalificacion(2);
        new SqlComentario().registrarComentario(cE.getComentario());
        
        new Timer(1_000, (e) -> { this.setVisible(false); this.dispose(); }).start();
    }//GEN-LAST:event_jButtonCalificacionExperienciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCalificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCalificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCalificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCalificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCalificacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAgradecimiento;
    private javax.swing.JPanel PanelCalificacionConductor;
    private javax.swing.JPanel PanelCalificacionExperiencia;
    private javax.swing.JPanel PanelCalificacionVehiculo;
    private javax.swing.JButton jButtonCalificacionConductor;
    private javax.swing.JButton jButtonCalificacionExperiencia;
    private javax.swing.JButton jButtonCalificacionVehiculo;
    private javax.swing.JComboBox<String> jComboBoxCalificacionConductor;
    private javax.swing.JComboBox<String> jComboBoxCalificacionExperiencia;
    private javax.swing.JComboBox<String> jComboBoxCalificacionVehiculo;
    private javax.swing.JLabel jLabelAgradecimiento;
    private javax.swing.JLabel jLabelAgradecimiento1;
    private javax.swing.JLabel jLabelCalificacionConductor;
    private javax.swing.JLabel jLabelCalificacionExperiencia;
    private javax.swing.JLabel jLabelCalificacionVehiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaCalificacionExperiencia;
    // End of variables declaration//GEN-END:variables
}
