/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.usuarios;

import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import modelo.ranking.Calificacion;
import modelo.usuarios.Conductor;
import vistas.ranking.JFrameCalificacion;
import vistas.ranking.JFrameRanking;
import vistas.viaje.JFContabilizadorRutas;
import vistas.viaje.JFCrearViaje;
import vistas.viaje.JFListaViajesDeConductor;

/**
 *
 * @author Lenovo
 */
public class JFConductor extends javax.swing.JFrame {

    Conductor conductor;

    /**
     * Creates new form JFCuentaConductor
     */
    public JFConductor(Conductor conductor) {
        initComponents();
        setLocationRelativeTo(null);

        this.conductor = conductor;

        txtNombre.setText(conductor.getUsuario().getNombre());
        txtApellido.setText(conductor.getUsuario().getApellido());
        txtCodigoUnico.setText(conductor.getUsuario().getCodUnico() + "");
        txtTelefono.setText(conductor.getUsuario().getTelefono());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblCodigoUnico = new javax.swing.JLabel();
        txtCodigoUnico = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnCrearViaje = new javax.swing.JButton();
        btnVerViajes = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        lblCuentaConductor = new javax.swing.JLabel();
        btnRutas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setText("Nombre");

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });

        lblApellido.setText("Apellido");

        txtApellido.setEditable(false);
        txtApellido.setBackground(new java.awt.Color(255, 255, 255));

        lblCodigoUnico.setText("Código Único");

        txtCodigoUnico.setEditable(false);
        txtCodigoUnico.setBackground(new java.awt.Color(255, 255, 255));

        lblTelefono.setText("Teléfono");

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));

        btnCrearViaje.setText("Crear viaje");
        btnCrearViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearViajeActionPerformed(evt);
            }
        });

        btnVerViajes.setText("Ver lista de viajes");
        btnVerViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerViajesActionPerformed(evt);
            }
        });

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        lblCuentaConductor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCuentaConductor.setText("Cuenta Conductor");

        btnRutas.setText("Ver rutas frecuentes");
        btnRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCuentaConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesion)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCodigoUnico)
                                .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCrearViaje))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtCodigoUnico, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRutas)
                                .addGap(33, 33, 33)
                                .addComponent(btnVerViajes)))
                        .addContainerGap(170, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarSesion)
                    .addComponent(lblCuentaConductor))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigoUnico)
                    .addComponent(txtCodigoUnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearViaje)
                    .addComponent(btnVerViajes)
                    .addComponent(btnRutas))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearViajeActionPerformed

        if (conductor.getPenalizacion().verificarPenalizacion()) {
            DateTimeFormatter formatterLS = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            JOptionPane.showMessageDialog(null, "Conductor penalizado hasta: " + conductor.getPenalizacion().getFecha().getFechaYHora().format(formatterLS), "Aviso", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        setVisible(false);
        JFCrearViaje jFCrearViaje = new JFCrearViaje(conductor);
        jFCrearViaje.setVisible(true);
    }//GEN-LAST:event_btnCrearViajeActionPerformed

    private void btnVerViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerViajesActionPerformed
        // TODO add your handling code here:
        setVisible(false);

        JFListaViajesDeConductor jFListaViajesDeConductor = new JFListaViajesDeConductor(conductor);

        jFListaViajesDeConductor.setVisible(true);
    }//GEN-LAST:event_btnVerViajesActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        setVisible(false);
        
        conductor.getUsuario().cerrarSesion();
        JFLogin jFLogin = new JFLogin();
        jFLogin.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutasActionPerformed
        setVisible(false);

        JFContabilizadorRutas jFContabilizadorRutas = new JFContabilizadorRutas(conductor);
        jFContabilizadorRutas.setVisible(true);
    }//GEN-LAST:event_btnRutasActionPerformed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        // TODO add your handling code here:
        new JFrameRanking(conductor.getUsuario().getCodUnico()).setVisible(true);
    }//GEN-LAST:event_txtNombreMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCrearViaje;
    private javax.swing.JButton btnRutas;
    private javax.swing.JButton btnVerViajes;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCodigoUnico;
    private javax.swing.JLabel lblCuentaConductor;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCodigoUnico;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
