/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.usuarios;

import controladorBD.ranking.SqlCalificacion;
import controladorBD.reservacion.SqlReservacion;
import controladorBD.usuarios.SqlCuenta;
import controladorBD.usuarios.SqlUsuario;
import controladorBD.usuarios.SqlVehiculo;
import controladorBD.viaje.SqlViaje;
import java.util.HashMap;
import javax.swing.JOptionPane;
import modelo.reservacion.Reservacion;
import modelo.usuarios.Conductor;
import modelo.usuarios.Cuenta;
import modelo.usuarios.Pasajero;
import modelo.usuarios.Usuario;
import modelo.usuarios.Vehiculo;
import modelo.viaje.Viaje;

/**
 *
 * @author Lenovo
 */
public class JFLogin extends javax.swing.JFrame {

    public static String correo = "";
    public static String contrasenia = "";
    public static String tipoCuenta = "";
    public static HashMap<String, Vehiculo> vehiculos;
    public static HashMap<Integer, Usuario> usuarios;
    public static HashMap<Integer, Cuenta> cuentas;
    public static HashMap<Integer, Viaje> viajes;
    public static HashMap<Integer, Reservacion> reservaciones;

    SqlVehiculo sqlVehiculo = new SqlVehiculo();
    SqlUsuario sqlUsuario = new SqlUsuario();
    SqlCuenta sqlCuenta = new SqlCuenta();
    SqlViaje sqlViaje = new SqlViaje();
    SqlReservacion sqlReservacion = new SqlReservacion();
    SqlCalificacion sqlCalificacion = new SqlCalificacion();
    
    
    /**
     * Creates new form JFLogin
     */
    public JFLogin() {
        initComponents();
        setLocationRelativeTo(null);

        vehiculos = sqlVehiculo.obtenerVehiculos();
        usuarios = sqlUsuario.obtenerUsuarios();
        cuentas = sqlCuenta.obtenerCuentas(usuarios, vehiculos);
        viajes = sqlViaje.obtenerViajes(cuentas);
        reservaciones = sqlReservacion.obtenerReservaciones(viajes, cuentas);
        
        sqlCalificacion.obtenerCalificación(viajes, cuentas);
        sqlCalificacion.obtenerPenalizacion(cuentas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCorreo = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbTipoCuenta = new javax.swing.JComboBox<>();
        psswdContrasenia = new javax.swing.JPasswordField();
        jButtonRegistrarse = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCorreo.setText("Correo");

        lblContrasenia.setText("Contraseña");
        lblContrasenia.setToolTipText("");

        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de cuenta");

        cmbTipoCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pasajero", "Conductor" }));
        cmbTipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoCuentaActionPerformed(evt);
            }
        });

        jButtonRegistrarse.setText("Registrate");
        jButtonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarseActionPerformed(evt);
            }
        });

        jLabel2.setText("¿No tienes una cuenta?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblContrasenia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(psswdContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(cmbTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRegistrarse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel2)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasenia)
                    .addComponent(psswdContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addComponent(btnIniciarSesion)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRegistrarse)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
        correo = txtCorreo.getText();
        contrasenia = new String(psswdContrasenia.getPassword());
        tipoCuenta = cmbTipoCuenta.getSelectedItem().toString();
        boolean bandera=false;

        for (int idcuenta : cuentas.keySet()) {
            Cuenta cuentaTemp = cuentas.get(idcuenta);
            if (tipoCuenta.equals("Pasajero")) {
                if (!(cuentaTemp instanceof Pasajero)) {
                    continue;
                }
            } else {
                if (!(cuentaTemp instanceof Conductor)) {
                    continue;
                }
            }
            if (correo.equals(cuentaTemp.getCorreo())) {
                if (cuentaTemp.getUsuario().iniciarSesion(correo, contrasenia, cuentaTemp)) {
                    JOptionPane.showMessageDialog(null, "Bienvenido", "Aviso", JOptionPane.INFORMATION_MESSAGE);

                    if (tipoCuenta.equals("Pasajero")) {
                        JFPasajero jfpasajero = new JFPasajero((Pasajero) cuentaTemp);
                        jfpasajero.setVisible(true);
                        this.setVisible(false);
                    } else {
                        JFConductor jfconductor = new JFConductor((Conductor) cuentaTemp);
                        jfconductor.setVisible(true);
                        this.setVisible(false);
                    }
                    bandera=true;
                    break;
                } else {
                    //JOptionPane.showMessageDialog(null, "Credenciales incorrectas1", "Error", JOptionPane.ERROR_MESSAGE);
                }
                break;
            }
        }
        if (!bandera){
            JOptionPane.showMessageDialog(null, "Credenciales incorrectas", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void jButtonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarseActionPerformed
        this.setVisible(false);
        JFRegistro jfregistro = new JFRegistro();
        jfregistro.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrarseActionPerformed

    private void cmbTipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoCuentaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JComboBox<String> cmbTipoCuenta;
    private javax.swing.JButton jButtonRegistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JPasswordField psswdContrasenia;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
