/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.usuarios;

import controladorBD.usuarios.SqlUsuario;
import controladorBD.usuarios.SqlVehiculo;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import modelo.usuarios.Conductor;
import modelo.usuarios.Cuenta;
import modelo.usuarios.Pasajero;
import modelo.usuarios.Usuario;
import modelo.usuarios.Vehiculo;
import vistas.usuarios.JFRegistro;

/**
 *
 * @author Lenovo
 */
public class JFVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form JFVehiculo
     */
    public static String placa;
    public static String modelo;
    public static String color;
    public static int anio;
    public static int numeroAsientos;
    public Vehiculo vehiculo;
    public static String correo;
    public static String contrasenia;
    public static Usuario nuevoUsuario;

    public JFVehiculo() {

        initComponents();
        setLocationRelativeTo(null);
        //this.btnRegistrarVehiculo.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlaca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        lblNumeroAsientos = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtNumeroAsientos = new javax.swing.JTextField();
        btnRegistrarVehiculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPlaca.setText("Placa");

        lblModelo.setText("Modelo");

        lblColor.setText("Color");

        lblAnio.setText("Año");

        lblNumeroAsientos.setText("Número de asientos");

        txtPlaca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPlacaFocusLost(evt);
            }
        });
        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlacaKeyTyped(evt);
            }
        });

        txtColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorKeyTyped(evt);
            }
        });

        txtAnio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAnioFocusLost(evt);
            }
        });
        txtAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnioKeyTyped(evt);
            }
        });

        txtNumeroAsientos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroAsientosFocusLost(evt);
            }
        });
        txtNumeroAsientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumeroAsientosMouseClicked(evt);
            }
        });
        txtNumeroAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroAsientosActionPerformed(evt);
            }
        });
        txtNumeroAsientos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroAsientosKeyTyped(evt);
            }
        });

        btnRegistrarVehiculo.setText("Registrar Vehículo");
        btnRegistrarVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarVehiculoMouseClicked(evt);
            }
        });
        btnRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(lblColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(lblNumeroAsientos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAnio)
                            .addComponent(txtPlaca)
                            .addComponent(txtModelo)
                            .addComponent(txtColor)
                            .addComponent(txtNumeroAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(btnRegistrarVehiculo)))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColor)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnio)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroAsientos)
                    .addComponent(txtNumeroAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addComponent(btnRegistrarVehiculo)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    public void habilitarRegistro(){
        if(!txtPlaca.getText().isEmpty() && !txtModelo.getText().isEmpty()
                && !txtColor.getText().isEmpty() 
                && !txtAnio.getText().isEmpty() 
                && !txtNumeroAsientos.getText().isEmpty()){
            btnRegistrarVehiculo.setEnabled(true);
        }
    }
    */

    private void btnRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVehiculoActionPerformed
        placa = txtPlaca.getText();
        modelo = txtModelo.getText();
        color = txtColor.getText();
        anio = Integer.parseInt(txtAnio.getText());
        numeroAsientos = Integer.parseInt(txtNumeroAsientos.getText());

        if(numeroAsientos <= 0){
            JOptionPane.showMessageDialog(rootPane, "Solo se puede ingresar enteros positivos");
            txtNumeroAsientos.requestFocus();
        }else{
            vehiculo = new Vehiculo(placa, modelo, color, anio, numeroAsientos);
        
        
        //JFRegistro jfregistro = new JFRegistro();
        contrasenia = JFRegistro.contrasenia;

        correo = JFRegistro.correo;

        nuevoUsuario = JFRegistro.nuevoUsuario;

        

        SqlVehiculo modSql = new SqlVehiculo();
        try {
            if (modSql.registrarVehiculo(vehiculo)) {
                Cuenta cuentaConductor = new Conductor(correo, contrasenia, nuevoUsuario, vehiculo);
                Cuenta cuentaPasajero = new Pasajero(correo, contrasenia, nuevoUsuario, 0.0);
                SqlUsuario modSql2 = new SqlUsuario();
                SqlUsuario modSql3 = new SqlUsuario();
                try {
                    if ((modSql2.registrarUsuario(nuevoUsuario))) {
                        if ((modSql2.registrarConductor(nuevoUsuario, cuentaConductor, "Conductor", placa))) {
                            if ((modSql2.registrarPasajero(nuevoUsuario, cuentaPasajero, "Pasajero"))) {
                                JOptionPane.showMessageDialog(null, "Conductor y vehiculo registrados exitosamente!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                            } else {
                                JOptionPane.showMessageDialog(null, "No se pudo registrar pasajero", "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "No se pudo registrar conductor", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "No se pudo registrar usuario", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Credenciales incorrectas", "Error", JOptionPane.ERROR_MESSAGE);
                }
                //JOptionPane.showMessageDialog(null, "Conductor registrado exitosamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                JFLogin login = new JFLogin();
                login.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo registrar el vehiculo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en el registro", "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnRegistrarVehiculoActionPerformed

    private void txtAnioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnioFocusLost
        if(Integer.parseInt(txtAnio.getText())>2008 && Integer.parseInt(txtAnio.getText())<=2023){
            txtNumeroAsientos.requestFocus();
        }else{
            JOptionPane.showMessageDialog(null, "Solo se puede ingresar vehiculos entre los años 2008 y 2023");
            txtAnio.requestFocus();
        
        }
    }//GEN-LAST:event_txtAnioFocusLost

    private void txtNumeroAsientosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroAsientosKeyTyped
        char validacion1=evt.getKeyChar();
        if(Character.isLetter(validacion1)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se permiten Numeros");
        }       
    }//GEN-LAST:event_txtNumeroAsientosKeyTyped

    private void txtNumeroAsientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroAsientosMouseClicked
        
        
    }//GEN-LAST:event_txtNumeroAsientosMouseClicked

    private void txtNumeroAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroAsientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroAsientosActionPerformed

    private void btnRegistrarVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarVehiculoMouseClicked
        
    }//GEN-LAST:event_btnRegistrarVehiculoMouseClicked

    private void txtNumeroAsientosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroAsientosFocusLost
        
        
    }//GEN-LAST:event_txtNumeroAsientosFocusLost

    private void txtPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPlacaKeyTyped

    private void txtColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorKeyTyped
        // TODO add your handling code here:
        char validacion1 = evt.getKeyChar();
        if(Character.isDigit(validacion1)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se permiten letras");  
        }
    }//GEN-LAST:event_txtColorKeyTyped

    private void txtAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnioKeyTyped
        // TODO add your handling code here:
        char validacion1=evt.getKeyChar();
        if(Character.isLetter(validacion1)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se permiten números");
        }   
    }//GEN-LAST:event_txtAnioKeyTyped
    
    public boolean validarPlaca(String placa){
        String validarPlaca = "^[A-Z]{3}\\d{3,4}$";
        Pattern pattern = Pattern.compile(validarPlaca);
        Matcher matcher = pattern.matcher(placa);
        return matcher.matches();
    }
    private void txtPlacaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacaFocusLost
        // TODO add your handling code here:
        if(validarPlaca(txtPlaca.getText()) == true){
            this.txtModelo.requestFocus();            
        }else{
            JOptionPane.showMessageDialog(rootPane, "La placa ingresada no es válida");
            txtPlaca.requestFocus();
        }
        
    }//GEN-LAST:event_txtPlacaFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarVehiculo;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNumeroAsientos;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNumeroAsientos;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
