/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.viaje;

import controladorBD.viaje.SqlViaje;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
import modelo.usuarios.Conductor;
import modelo.viaje.ListaViaje;
import modelo.viaje.Viaje;
import vistas.reservacion.JFListaReservacionPasajero;
import vistas.reservacion.JFListaReservacionesConductor;
import vistas.usuarios.JFConductor;

/**
 *
 * @author Dana
 */
public class JFListaViajesDeConductor extends javax.swing.JFrame {

    Conductor conductor;
    ListaViaje listaViaje;

    /**
     * Creates new form JFListaViajeConductor
     */
    public JFListaViajesDeConductor(Conductor conductor) {
        initComponents();
        setLocationRelativeTo(null);

        this.conductor = conductor;
        
        listaViaje = conductor.getListaViaje();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Partida");
        model.addColumn("Destino");
        model.addColumn("Fecha");
        model.addColumn("Hora");

        tblViajes.setModel(model);

        String[] fila = new String[4];

        for (Viaje viaje : listaViaje.getViajes()) {
            if (viaje != null) {
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                String fechaHora = viaje.getFecha().getFechaYHora().format(formatter);

                fila[0] = viaje.getUbicacionPartida();
                fila[1] = viaje.getUbicacionDestino();
                fila[2] = fechaHora.substring(0, 10);
                fila[3] = fechaHora.substring(11);
                model.addRow(fila);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        scrTablaViajes = new javax.swing.JScrollPane();
        tblViajes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("LISTA DE VIAJES");

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar.setText("Volver");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        tblViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Partida", "Destino", "Fecha"
            }
        ));
        tblViajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViajesMouseClicked(evt);
            }
        });
        scrTablaViajes.setViewportView(tblViajes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(scrTablaViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(btnRegresar)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(scrTablaViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
        JFConductor jFConductor = new JFConductor(conductor);
        
        jFConductor.setVisible(true);
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void tblViajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViajesMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        
        int filaSeleccionada = tblViajes.rowAtPoint(evt.getPoint());
        Viaje[] viajes = listaViaje.getViajes();
        JFListaReservacionesConductor jFListaReservacionesConductor = new JFListaReservacionesConductor(viajes[filaSeleccionada]);
        
        jFListaReservacionesConductor.setVisible(true);
        
    }//GEN-LAST:event_tblViajesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFListaViajesDeConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFListaViajesDeConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFListaViajesDeConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFListaViajesDeConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //ew JFListaViajesDeConductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scrTablaViajes;
    private javax.swing.JTable tblViajes;
    // End of variables declaration//GEN-END:variables
}
